apiVersion: apps/v1
kind: Deployment
metadata:
  name: jp-springboot
  namespace: graddle
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jp-springboot
  template:
    metadata:
      labels:
        app: jp-springboot
    spec:
      containers:
        - name: springboot
          image: genesispatil/graddleapp:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: jp-springboot
  namespace: graddle
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jp-springboot
